### PR TITLE
update the section background color

### PR DESCRIPTION
**Pull request by ezhupa99**
## Checklist

- [x] Include screenshots if it is a frontend change
- [ ] The change is deployed to Staging with proper environment variable set
- [ ] If there is a new environment variable is the .env.example documented on where to fetch and set it
- [ ] If it is a settings change is there an account ready on staging that can be tested in that state

image

fixes this issue: #1306

### CODE REVIEW

**Comment by sandrodesouza** [comment]
@ezhupa99 thanks. Lets just remove the bg- tag. It will work for both dark and light mode.

**Comment by ezhupa99** [comment]
Okay, will do that

**Comment by ezhupa99** [comment]
@sandrodesouza it's done

**Comment by emilos** [comment]
Thanks!

**Pull request merged**
